### ISSUE TITLE
Implement time-filtering in get_codelist()

### ISSUE THREAD

**Issue by petrbouchal** [petrbouchal/statnipokladna#10]
... to make sure the user does not get duplicate or obsolete rows
- should filter for today by default (but this can cause the user problems with reproducibility as they get different data on different dates - we can either not filter by default or document and warn)

**Comment by petrbouchal** [comment]
or it can be done in the future `add_codelist()` functions

**Comment by jlacko** [comment]
Introducing a date type parameter defaulting to today - but allowing for other dates - might be a way around this.
It would allow both a serious, reproducible, workflow with the parameter specified, and a quick glance when left blank (and relying on default `= Sys.Date()`).

**Comment by petrbouchal** [comment]
Just what I was thinking - but also think the function should produce a warning if the parameter is not set

**Comment by jlacko** [comment]
Or perhaps a message - with the function parameter defaulting to NULL, and inside the function an if block testing that for value NULL a message is displayed saying that no value was specified, returning current result - but beware dear user, your code may not reproduce later!

**Comment by petrbouchal** [comment]
That might work. Slight difficulty is in determining what the latest available dataset is (as there is no fixed date when they are released.) Waiting for new release of the SP website - that should contain a registry of available datasets.

**Comment by petrbouchal** [comment]
I ended up handling this in add_codelist. get_codelist always downloads the whole codelist; the filtering happens in add_codelist when joining the codelist to the data and is driven by the date information in the data.
