### ISSUE TITLE
Explore if we can provide cross-session storage

### ISSUE THREAD

**Issue by petrbouchal** [petrbouchal/statnipokladna#14]
...to limit redownloads. Perhaps by allowing user to say that file should be stored in working directory? That would be a dependency-free (without `rappdirs`) way that is hopefully CRAN-compliant.

**Comment by jlacko** [comment]
Persistent caching (i.e. outside of TEMPDIR) is not compliant with CRAN repository policy https://cran.r-project.org/web/packages/policies.html - to quote verbatim: Packages should not write in the user’s home filespace (including clipboards), nor anywhere else on the file system apart from the R session’s temporary directory (or during installation in the location pointed to by TMPDIR: and such usage should be cleaned up). Installing into the system’s R installation (e.g., scripts to its bin directory) is not allowed.
