### ISSUE TITLE
refactoring of codebook tables

### ISSUE THREAD

**Issue by jlacko** [petrbouchal/statnipokladna#15]
Wouldn't it be a good idea to remove the codebook definitions from scripts - e.g. sp_tables_i in tables.R - to a common init script, suppose data_raw.R - and have it stored as internal rds files via usethis::use_data()?

**Comment by petrbouchal** [comment]
Is there a reason other than aesthetics/organisation? I've found it useful to keep it next to the functions while developing, but feel free to submit a PR with a cleanup...

**Comment by jlacko** [comment]
It makes for cleaner code; function is of course the same. I was considering a PR to refactor that over the vacations, but now I am busy with other activities (life happens).
Closing as irrelevant
