### ISSUE TITLE
Streamline and document default date choice in get_table

### ISSUE THREAD

**Issue by petrbouchal** [petrbouchal/statnipokladna#16]
default year and month should be NULL
then if NULL
   determine and use latest available
   and warn/message about reproducibility

also need to handle weird combinations (month set, year not set; what month to use if year is set but not month?)

**Comment by jlacko** [comment]
you might consider having just one parameter - a date. The day part can be easily truncated, and the month & year parts are guaranteed to make formal sense (year always present, month always present, no month 13 etc.)

**Comment by petrbouchal** [comment]
In the end I decided to keep them as two parameters to make the time structure of the underlying data transparent to the user, plus a warning around defaults in non-interactive mode to aid reproducibility. Still need to automate checking the values/default against what data is actually available online, but that is pending on the data publisher revealing their API.
