### ISSUE TITLE
Correct info in Readme concerning saving the analysis

### ISSUE THREAD

**Issue by SmallhillCZ** [petrbouchal/statnipokladna#40]
"The online interface has no facility to save an analysis"

You can copy a link to the current analysis:
![Výstřižek](https://user-images.githubusercontent.com/1273865/73431434-b44af280-4340-11ea-9390-b584c8e20c15.PNG)

**Comment by petrbouchal** [comment]
Thanks - I genuinely did not notice that. Will clarify in the text.
